set = set()
int1 = int(input("Enter first integer: "))
set.add(int1)
int2 = int(input("Enter second integer: "))
set.add(int2)
int3 = int(input("Enter third integer: "))
set.add(int3)
int4 = int(input("Enter fourth integer: "))
set.add(int4)
print(set)
